# Generated by Django 5.1.4 on 2024-12-19 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripletRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('occurrences', models.IntegerField(default=1)),
                ('last_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
