# Generated by Django 5.1.4 on 2024-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('last_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
